#title: "Chaoran Liu 刘超然"
author: "Woman in Marketing Science"
description: "Chaoran Liu 刘超然"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: true             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:
  - {file: "index.md", title: "About", sidebaricon: home}
  - {url: "/assets/Resume_Sep_2025.pdf", title: "CV", icon: file-pdf}
  - {url: "https://www.liu-xiaomian.com", title: "Outside Academia", icon: link}

 

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Contact, icon: envelope, url: "mailto:chaoranl@pku.org.uk"}

  
sass:
  style: compressed

# Add this under your includes
include:
  - assets/css/custom.css

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
