title: "Chaoran Liu 刘超然"
author: "Chaoran Liu 刘超然"
description: "Chaoran Liu 刘超然"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: true             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:
  - {file: "index.md", title: "About", sidebaricon: home}
  - {url: "/assets/Resume_Sep_2025.pdf", title: "Download CV", icon: file-pdf}

 

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:chaoranl@pku.org.uk"}

  

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
